use crate::usage_table::UsageId;

// https://usb.org/sites/default/files/hut1_3_0.pdf - page 32
#[derive(Clone, Debug, PartialEq)]
pub enum GenericDesktopControlsUsage {
    Undefined,
    Pointer,
    Mouse,
    Joystick,
    Gamepad,
    Keyboard,
    Keypad,
    MultiaxisController,
    TabletPCSystemControls,
    WaterCoolingDevice,
    ComputerChassisDevice,
    WirelessRadioControls,
    PortableDeviceControl,
    SystemMultiAxisController,
    SpatialController,
    AssistiveControl,
    DeviceDock,
    DockableDevice,
    CallStateManagementControl,
    X,
    Y,
    Z,
    Rx,
    Ry,
    Rz,
    Slider,
    Dial,
    Wheel,
    HatSwitch,
    CountedBuffer,
    ByteCount,
    MotionWakeup,
    Start,
    Select,
    Vx,
    Vy,
    Vz,
    Vbrx,
    Vbry,
    Vbrz,
    Vno,
    FeatureNotification,
    ResolutionMultiplier,
    Qx,
    Qy,
    Qz,
    Qw,
    SystemControl,
    SystemPowerDown,
    SystemSleep,
    SystemWakeUp,
    SystemContextMenu,
    SystemMainMenu,
    SystemAppMenu,
    SystemMenuHelp,
    SystemMenuExit,
    SystemMenuSelect,
    SystemMenuRight,
    SystemMenuLeft,
    SystemMenuUp,
    SystemMenuDown,
    SystemColdRestart,
    SystemWarmRestart,
    DpadUp,
    DpadDown,
    DpadRight,
    DpadLeft,
    IndexTrigger,
    PalmTrigger,
    Thumbstick,
    SystemFunctionShift,
    SystemFunctionShiftLock,
    SystemFunctionShiftLockIndicator,
    SystemDismissNotification,
    SystemDoNotDisturb,
    SystemDock,
    SystemUndock,
    SystemSetup,
    SystemBreak,
    SystemDebuggerBreak,
    ApplicationBreak,
    ApplicationDebuggerBreak,
    SystemSpeakerMute,
    SystemHibernate,
    SystemDisplayInvert,
    SystemDisplayInternal,
    SystemDisplayExternal,
    SystemDisplayBoth,
    SystemDisplayDual,
    SystemDisplayToggleIntExtMode,
    SystemDisplaySwapPrimarySecondary,
    SystemDisplayToggleLCDAutoscale,
    SensorZone,
    RPM,
    CoolantLevel,
    CoolantCriticalLevel,
    CoolantPump,
    ChassisEnclosure,
    WirelessRadioButton,
    WirelessRadioLED,
    WirelessRadioSliderSwitch,
    SystemDisplayRotationLockButton,
    SystemDisplayRotationLockSliderSwitch,
    ControlEnable,
    DockableDeviceUniqueID,
    DockableDeviceVendorID,
    DockableDevicePrimaryUsagePage,
    DockableDevicePrimaryUsageID,
    DockableDeviceDockingState,
    DockableDeviceDisplayOcclusion,
    DockableDeviceObjectType,
    CallActiveLED,
    CallMuteToggle,
    CallMuteLED,
    Reserved(u16),
}

impl From<u16> for GenericDesktopControlsUsage {
    fn from(value: u16) -> Self {
        match value {
            0x00 => GenericDesktopControlsUsage::Undefined,
            0x01 => GenericDesktopControlsUsage::Pointer,
            0x02 => GenericDesktopControlsUsage::Mouse,
            0x04 => GenericDesktopControlsUsage::Joystick,
            0x05 => GenericDesktopControlsUsage::Gamepad,
            0x06 => GenericDesktopControlsUsage::Keyboard,
            0x07 => GenericDesktopControlsUsage::Keypad,
            0x08 => GenericDesktopControlsUsage::MultiaxisController,
            0x09 => GenericDesktopControlsUsage::TabletPCSystemControls,
            0x0A => GenericDesktopControlsUsage::WaterCoolingDevice,
            0x0B => GenericDesktopControlsUsage::ComputerChassisDevice,
            0x0C => GenericDesktopControlsUsage::WirelessRadioControls,
            0x0D => GenericDesktopControlsUsage::PortableDeviceControl,
            0x0E => GenericDesktopControlsUsage::SystemMultiAxisController,
            0x0F => GenericDesktopControlsUsage::SpatialController,
            0x10 => GenericDesktopControlsUsage::AssistiveControl,
            0x11 => GenericDesktopControlsUsage::DeviceDock,
            0x12 => GenericDesktopControlsUsage::DockableDevice,
            0x13 => GenericDesktopControlsUsage::CallStateManagementControl,
            0x30 => GenericDesktopControlsUsage::X,
            0x31 => GenericDesktopControlsUsage::Y,
            0x32 => GenericDesktopControlsUsage::Z,
            0x33 => GenericDesktopControlsUsage::Rx,
            0x34 => GenericDesktopControlsUsage::Ry,
            0x35 => GenericDesktopControlsUsage::Rz,
            0x36 => GenericDesktopControlsUsage::Slider,
            0x37 => GenericDesktopControlsUsage::Dial,
            0x38 => GenericDesktopControlsUsage::Wheel,
            0x39 => GenericDesktopControlsUsage::HatSwitch,
            0x3A => GenericDesktopControlsUsage::CountedBuffer,
            0x3B => GenericDesktopControlsUsage::ByteCount,
            0x3C => GenericDesktopControlsUsage::MotionWakeup,
            0x3D => GenericDesktopControlsUsage::Start,
            0x3E => GenericDesktopControlsUsage::Select,
            0x40 => GenericDesktopControlsUsage::Vx,
            0x41 => GenericDesktopControlsUsage::Vy,
            0x42 => GenericDesktopControlsUsage::Vz,
            0x43 => GenericDesktopControlsUsage::Vbrx,
            0x44 => GenericDesktopControlsUsage::Vbry,
            0x45 => GenericDesktopControlsUsage::Vbrz,
            0x46 => GenericDesktopControlsUsage::Vno,
            0x47 => GenericDesktopControlsUsage::FeatureNotification,
            0x48 => GenericDesktopControlsUsage::ResolutionMultiplier,
            0x49 => GenericDesktopControlsUsage::Qx,
            0x4A => GenericDesktopControlsUsage::Qy,
            0x4B => GenericDesktopControlsUsage::Qz,
            0x4C => GenericDesktopControlsUsage::Qw,
            0x80 => GenericDesktopControlsUsage::SystemControl,
            0x81 => GenericDesktopControlsUsage::SystemPowerDown,
            0x82 => GenericDesktopControlsUsage::SystemSleep,
            0x83 => GenericDesktopControlsUsage::SystemWakeUp,
            0x84 => GenericDesktopControlsUsage::SystemContextMenu,
            0x85 => GenericDesktopControlsUsage::SystemMainMenu,
            0x86 => GenericDesktopControlsUsage::SystemAppMenu,
            0x87 => GenericDesktopControlsUsage::SystemMenuHelp,
            0x88 => GenericDesktopControlsUsage::SystemMenuExit,
            0x89 => GenericDesktopControlsUsage::SystemMenuSelect,
            0x8A => GenericDesktopControlsUsage::SystemMenuRight,
            0x8B => GenericDesktopControlsUsage::SystemMenuLeft,
            0x8C => GenericDesktopControlsUsage::SystemMenuUp,
            0x8D => GenericDesktopControlsUsage::SystemMenuDown,
            0x8E => GenericDesktopControlsUsage::SystemColdRestart,
            0x8F => GenericDesktopControlsUsage::SystemWarmRestart,
            0x90 => GenericDesktopControlsUsage::DpadUp,
            0x91 => GenericDesktopControlsUsage::DpadDown,
            0x92 => GenericDesktopControlsUsage::DpadRight,
            0x93 => GenericDesktopControlsUsage::DpadLeft,
            0x94 => GenericDesktopControlsUsage::IndexTrigger,
            0x95 => GenericDesktopControlsUsage::PalmTrigger,
            0x96 => GenericDesktopControlsUsage::Thumbstick,
            0x97 => GenericDesktopControlsUsage::SystemFunctionShift,
            0x98 => GenericDesktopControlsUsage::SystemFunctionShiftLock,
            0x99 => GenericDesktopControlsUsage::SystemFunctionShiftLockIndicator,
            0x9A => GenericDesktopControlsUsage::SystemDismissNotification,
            0x9B => GenericDesktopControlsUsage::SystemDoNotDisturb,
            0xA0 => GenericDesktopControlsUsage::SystemDock,
            0xA1 => GenericDesktopControlsUsage::SystemUndock,
            0xA2 => GenericDesktopControlsUsage::SystemSetup,
            0xA3 => GenericDesktopControlsUsage::SystemBreak,
            0xA4 => GenericDesktopControlsUsage::SystemDebuggerBreak,
            0xA5 => GenericDesktopControlsUsage::ApplicationBreak,
            0xA6 => GenericDesktopControlsUsage::ApplicationDebuggerBreak,
            0xA7 => GenericDesktopControlsUsage::SystemSpeakerMute,
            0xA8 => GenericDesktopControlsUsage::SystemHibernate,
            0xB0 => GenericDesktopControlsUsage::SystemDisplayInvert,
            0xB1 => GenericDesktopControlsUsage::SystemDisplayInternal,
            0xB2 => GenericDesktopControlsUsage::SystemDisplayExternal,
            0xB3 => GenericDesktopControlsUsage::SystemDisplayBoth,
            0xB4 => GenericDesktopControlsUsage::SystemDisplayDual,
            0xB5 => GenericDesktopControlsUsage::SystemDisplayToggleIntExtMode,
            0xB6 => GenericDesktopControlsUsage::SystemDisplaySwapPrimarySecondary,
            0xB7 => GenericDesktopControlsUsage::SystemDisplayToggleLCDAutoscale,
            0xC0 => GenericDesktopControlsUsage::SensorZone,
            0xC1 => GenericDesktopControlsUsage::RPM,
            0xC2 => GenericDesktopControlsUsage::CoolantLevel,
            0xC3 => GenericDesktopControlsUsage::CoolantCriticalLevel,
            0xC4 => GenericDesktopControlsUsage::CoolantPump,
            0xC5 => GenericDesktopControlsUsage::ChassisEnclosure,
            0xC6 => GenericDesktopControlsUsage::WirelessRadioButton,
            0xC7 => GenericDesktopControlsUsage::WirelessRadioLED,
            0xC8 => GenericDesktopControlsUsage::WirelessRadioSliderSwitch,
            0xC9 => GenericDesktopControlsUsage::SystemDisplayRotationLockButton,
            0xCA => GenericDesktopControlsUsage::SystemDisplayRotationLockSliderSwitch,
            0xCB => GenericDesktopControlsUsage::ControlEnable,
            0xD0 => GenericDesktopControlsUsage::DockableDeviceUniqueID,
            0xD1 => GenericDesktopControlsUsage::DockableDeviceVendorID,
            0xD2 => GenericDesktopControlsUsage::DockableDevicePrimaryUsagePage,
            0xD3 => GenericDesktopControlsUsage::DockableDevicePrimaryUsageID,
            0xD4 => GenericDesktopControlsUsage::DockableDeviceDockingState,
            0xD5 => GenericDesktopControlsUsage::DockableDeviceDisplayOcclusion,
            0xD6 => GenericDesktopControlsUsage::DockableDeviceObjectType,
            0xE0 => GenericDesktopControlsUsage::CallActiveLED,
            0xE1 => GenericDesktopControlsUsage::CallMuteToggle,
            0xE2 => GenericDesktopControlsUsage::CallMuteLED,
            i => GenericDesktopControlsUsage::Reserved(i),
        }
    }
}

impl From<GenericDesktopControlsUsage> for u16 {
    fn from(value: GenericDesktopControlsUsage) -> Self {
        match value {
            GenericDesktopControlsUsage::Undefined => 0x00,
            GenericDesktopControlsUsage::Pointer => 0x01,
            GenericDesktopControlsUsage::Mouse => 0x02,
            GenericDesktopControlsUsage::Joystick => 0x04,
            GenericDesktopControlsUsage::Gamepad => 0x05,
            GenericDesktopControlsUsage::Keyboard => 0x06,
            GenericDesktopControlsUsage::Keypad => 0x07,
            GenericDesktopControlsUsage::MultiaxisController => 0x08,
            GenericDesktopControlsUsage::TabletPCSystemControls => 0x09,
            GenericDesktopControlsUsage::WaterCoolingDevice => 0x0A,
            GenericDesktopControlsUsage::ComputerChassisDevice => 0x0B,
            GenericDesktopControlsUsage::WirelessRadioControls => 0x0C,
            GenericDesktopControlsUsage::PortableDeviceControl => 0x0D,
            GenericDesktopControlsUsage::SystemMultiAxisController => 0x0E,
            GenericDesktopControlsUsage::SpatialController => 0x0F,
            GenericDesktopControlsUsage::AssistiveControl => 0x10,
            GenericDesktopControlsUsage::DeviceDock => 0x11,
            GenericDesktopControlsUsage::DockableDevice => 0x12,
            GenericDesktopControlsUsage::CallStateManagementControl => 0x13,
            GenericDesktopControlsUsage::X => 0x30,
            GenericDesktopControlsUsage::Y => 0x31,
            GenericDesktopControlsUsage::Z => 0x32,
            GenericDesktopControlsUsage::Rx => 0x33,
            GenericDesktopControlsUsage::Ry => 0x34,
            GenericDesktopControlsUsage::Rz => 0x35,
            GenericDesktopControlsUsage::Slider => 0x36,
            GenericDesktopControlsUsage::Dial => 0x37,
            GenericDesktopControlsUsage::Wheel => 0x38,
            GenericDesktopControlsUsage::HatSwitch => 0x39,
            GenericDesktopControlsUsage::CountedBuffer => 0x3A,
            GenericDesktopControlsUsage::ByteCount => 0x3B,
            GenericDesktopControlsUsage::MotionWakeup => 0x3C,
            GenericDesktopControlsUsage::Start => 0x3D,
            GenericDesktopControlsUsage::Select => 0x3E,
            GenericDesktopControlsUsage::Vx => 0x40,
            GenericDesktopControlsUsage::Vy => 0x41,
            GenericDesktopControlsUsage::Vz => 0x42,
            GenericDesktopControlsUsage::Vbrx => 0x43,
            GenericDesktopControlsUsage::Vbry => 0x44,
            GenericDesktopControlsUsage::Vbrz => 0x45,
            GenericDesktopControlsUsage::Vno => 0x46,
            GenericDesktopControlsUsage::FeatureNotification => 0x47,
            GenericDesktopControlsUsage::ResolutionMultiplier => 0x48,
            GenericDesktopControlsUsage::Qx => 0x49,
            GenericDesktopControlsUsage::Qy => 0x4A,
            GenericDesktopControlsUsage::Qz => 0x4B,
            GenericDesktopControlsUsage::Qw => 0x4C,
            GenericDesktopControlsUsage::SystemControl => 0x80,
            GenericDesktopControlsUsage::SystemPowerDown => 0x81,
            GenericDesktopControlsUsage::SystemSleep => 0x82,
            GenericDesktopControlsUsage::SystemWakeUp => 0x83,
            GenericDesktopControlsUsage::SystemContextMenu => 0x84,
            GenericDesktopControlsUsage::SystemMainMenu => 0x85,
            GenericDesktopControlsUsage::SystemAppMenu => 0x86,
            GenericDesktopControlsUsage::SystemMenuHelp => 0x87,
            GenericDesktopControlsUsage::SystemMenuExit => 0x88,
            GenericDesktopControlsUsage::SystemMenuSelect => 0x89,
            GenericDesktopControlsUsage::SystemMenuRight => 0x8A,
            GenericDesktopControlsUsage::SystemMenuLeft => 0x8B,
            GenericDesktopControlsUsage::SystemMenuUp => 0x8C,
            GenericDesktopControlsUsage::SystemMenuDown => 0x8D,
            GenericDesktopControlsUsage::SystemColdRestart => 0x8E,
            GenericDesktopControlsUsage::SystemWarmRestart => 0x8F,
            GenericDesktopControlsUsage::DpadUp => 0x90,
            GenericDesktopControlsUsage::DpadDown => 0x91,
            GenericDesktopControlsUsage::DpadRight => 0x92,
            GenericDesktopControlsUsage::DpadLeft => 0x93,
            GenericDesktopControlsUsage::IndexTrigger => 0x94,
            GenericDesktopControlsUsage::PalmTrigger => 0x95,
            GenericDesktopControlsUsage::Thumbstick => 0x96,
            GenericDesktopControlsUsage::SystemFunctionShift => 0x97,
            GenericDesktopControlsUsage::SystemFunctionShiftLock => 0x98,
            GenericDesktopControlsUsage::SystemFunctionShiftLockIndicator => 0x99,
            GenericDesktopControlsUsage::SystemDismissNotification => 0x9A,
            GenericDesktopControlsUsage::SystemDoNotDisturb => 0x9B,
            GenericDesktopControlsUsage::SystemDock => 0xA0,
            GenericDesktopControlsUsage::SystemUndock => 0xA1,
            GenericDesktopControlsUsage::SystemSetup => 0xA2,
            GenericDesktopControlsUsage::SystemBreak => 0xA3,
            GenericDesktopControlsUsage::SystemDebuggerBreak => 0xA4,
            GenericDesktopControlsUsage::ApplicationBreak => 0xA5,
            GenericDesktopControlsUsage::ApplicationDebuggerBreak => 0xA6,
            GenericDesktopControlsUsage::SystemSpeakerMute => 0xA7,
            GenericDesktopControlsUsage::SystemHibernate => 0xA8,
            GenericDesktopControlsUsage::SystemDisplayInvert => 0xB0,
            GenericDesktopControlsUsage::SystemDisplayInternal => 0xB1,
            GenericDesktopControlsUsage::SystemDisplayExternal => 0xB2,
            GenericDesktopControlsUsage::SystemDisplayBoth => 0xB3,
            GenericDesktopControlsUsage::SystemDisplayDual => 0xB4,
            GenericDesktopControlsUsage::SystemDisplayToggleIntExtMode => 0xB5,
            GenericDesktopControlsUsage::SystemDisplaySwapPrimarySecondary => 0xB6,
            GenericDesktopControlsUsage::SystemDisplayToggleLCDAutoscale => 0xB7,
            GenericDesktopControlsUsage::SensorZone => 0xC0,
            GenericDesktopControlsUsage::RPM => 0xC1,
            GenericDesktopControlsUsage::CoolantLevel => 0xC2,
            GenericDesktopControlsUsage::CoolantCriticalLevel => 0xC3,
            GenericDesktopControlsUsage::CoolantPump => 0xC4,
            GenericDesktopControlsUsage::ChassisEnclosure => 0xC5,
            GenericDesktopControlsUsage::WirelessRadioButton => 0xC6,
            GenericDesktopControlsUsage::WirelessRadioLED => 0xC7,
            GenericDesktopControlsUsage::WirelessRadioSliderSwitch => 0xC8,
            GenericDesktopControlsUsage::SystemDisplayRotationLockButton => 0xC9,
            GenericDesktopControlsUsage::SystemDisplayRotationLockSliderSwitch => 0xCA,
            GenericDesktopControlsUsage::ControlEnable => 0xCB,
            GenericDesktopControlsUsage::DockableDeviceUniqueID => 0xD0,
            GenericDesktopControlsUsage::DockableDeviceVendorID => 0xD1,
            GenericDesktopControlsUsage::DockableDevicePrimaryUsagePage => 0xD2,
            GenericDesktopControlsUsage::DockableDevicePrimaryUsageID => 0xD3,
            GenericDesktopControlsUsage::DockableDeviceDockingState => 0xD4,
            GenericDesktopControlsUsage::DockableDeviceDisplayOcclusion => 0xD5,
            GenericDesktopControlsUsage::DockableDeviceObjectType => 0xD6,
            GenericDesktopControlsUsage::CallActiveLED => 0xE0,
            GenericDesktopControlsUsage::CallMuteToggle => 0xE1,
            GenericDesktopControlsUsage::CallMuteLED => 0xE2,
            GenericDesktopControlsUsage::Reserved(i) => i,
        }
    }
}

impl UsageId for GenericDesktopControlsUsage {
    fn usage_id(self) -> u16 {
        self.into()
    }
}
